### ISSUE TITLE
Allow comments in default packages

### ISSUE THREAD

**Issue by spywhere** [danhper/asdf-python#105]
It would be great if we could have support for comments in the `.default-python-packages` file.

If the implementation does also support an empty line, that would be even better. But that's not mandatory for my use case here.

This way, I could add some comments. For example, why do I need this particular package?

**Comment by erikw** [comment]
I would very much like this feature as well! It's important to be able to document on why I need a package (easy to forget when coming back to it after a while.)

`asdf-ruby` has support for blank and comment lines:
https://github.com/asdf-vm/asdf-ruby/blob/c6db9a376d1b01af9a5028f11fdfb96ab8902d60/bin/install#L100-L104
