### ISSUE TITLE
Error installing Python on OS X Mojave

### ISSUE THREAD

**Issue by geowa4** [danhper/asdf-python#43]
I tried installing both 3.7.1 and 3.6.7 with the same result shown below. It seems Mojave may have removed zlib: https://stackoverflow.com/questions/48288658/zipimport-zipimporterror-cant-decompress-data-zlib-not-available#comment92859734_50370494.

```
asdf install python 3.6.7
python-build 3.6.7 /Users/geowa4/.asdf/installs/python/3.6.7
python-build: use openssl from homebrew
python-build: use readline from homebrew
Downloading Python-3.6.7.tar.xz...
-> https://www.python.org/ftp/python/3.6.7/Python-3.6.7.tar.xz
Installing Python-3.6.7...
python-build: use readline from homebrew

BUILD FAILED (OS X 10.14 using python-build 1.2.7-11-g835707da)

Inspect or clean up the working tree at /var/folders/p6/2v_qbpvs41dd7yq9c3g2cqvh0000gn/T/python-build.20181026220617.38974
Results logged to /var/folders/p6/2v_qbpvs41dd7yq9c3g2cqvh0000gn/T/python-build.20181026220617.38974.log

Last 10 log lines:
  File "/private/var/folders/p6/2v_qbpvs41dd7yq9c3g2cqvh0000gn/T/python-build.20181026220617.38974/Python-3.6.7/Lib/ensurepip/__main__.py", line 5, in <module>
    sys.exit(ensurepip._main())
  File "/private/var/folders/p6/2v_qbpvs41dd7yq9c3g2cqvh0000gn/T/python-build.20181026220617.38974/Python-3.6.7/Lib/ensurepip/__init__.py", line 204, in _main
    default_pip=args.default_pip,
  File "/private/var/folders/p6/2v_qbpvs41dd7yq9c3g2cqvh0000gn/T/python-build.20181026220617.38974/Python-3.6.7/Lib/ensurepip/__init__.py", line 117, in _bootstrap
    return _run_pip(args + [p[0] for p in _PROJECTS], additional_paths)
  File "/private/var/folders/p6/2v_qbpvs41dd7yq9c3g2cqvh0000gn/T/python-build.20181026220617.38974/Python-3.6.7/Lib/ensurepip/__init__.py", line 27, in _run_pip
    import pip._internal
zipimport.ZipImportError: can't decompress data; zlib not available
make: *** [install] Error 1
```

**Comment by geowa4** [comment]
Thanks, that worked for me as well!

**Comment by evantravers** [comment]
I also am getting similar problems…

**Comment by esselius** [comment]
Not sure what fixed this for me, but I ran these things in this order:

```
$ asdf install python 3.7.1
# FAIL

$ brew install -s python
# FAIL: "Please reinstall readline. Sorry :("

$ brew reinstall readline
$ brew install -s python
# SUCCESS

$ brew uninstall python
$ asdf install python 3.7.1
# SUCCESS
```

**Comment by dipnlik** [comment]
I was having the SSL issue even after trying `brew reinstall readline` and other suggestions and `brew reinstall -s python` solved it, even without `brew uninstall python`.  Not sure if `-s` was really required or not.

Noticed that `brew install python` also installs `pkg-config` so maybe this package is related to the issue?  It is a little weird having to install Homebrew's python to be able to install asdf's python.

**Comment by MrPaulAR** [comment]
I too am having issues and hoping someone sees the error in my ways.

```
asdf install python 3.6.8                                                                                                        1247ms  Fri Jan  4 10:53:13 2019
python-build 3.6.8 /Users/paulthomas/.asdf/installs/python/3.6.8
python-build: use openssl from homebrew
python-build: use readline from homebrew
Downloading Python-3.6.8.tar.xz...
-> https://www.python.org/ftp/python/3.6.8/Python-3.6.8.tar.xz
Installing Python-3.6.8...
python-build: use readline from homebrew

BUILD FAILED (OS X 10.14.2 using python-build 1.2.8-12-g775a4b63)

Inspect or clean up the working tree at /var/folders/lf/zzyy185j7bzd9c540qp_46ww0000gp/T/python-build.20190104105327.83497
Results logged to /var/folders/lf/zzyy185j7bzd9c540qp_46ww0000gp/T/python-build.20190104105327.83497.log

Last 10 log lines:
      _test_repeated_init_and_subinterpreters in _testembed.o
  "_Py_SetProgramName", referenced from:
      _test_forced_io_encoding in _testembed.o
      _test_repeated_init_and_subinterpreters in _testembed.o
      _test_pre_initialization_api in _testembed.o
  "_Py_SetStandardStreamEncoding", referenced from:
      _test_forced_io_encoding in _testembed.o
ld: symbol(s) not found for architecture x86_64
clang: error: linker command failed with exit code 1 (use -v to see invocation)
make: *** [Programs/_testembed] Error 1
```

Below are the steps that I've done
I've set the build flags as defined above for LDFLAGS, CPPFLAGS, PKG_CONFIG_PATH, & KEEP_BUILD_PATH
Reinstalled zlib (brew reinstall zlib)
Reinstalled pythong (brew reinstall -s python)
Ran brew doctor and fixed findutils

I'm still getting the same error.

I can download the tarball from python's website and successfully compile it.  I didn't install.

**Comment by pikeas** [comment]
Same issue under Mojave 10.14.2 when install Python 3.7.2. Tinkered with adding openssl/zlib via homebrew and various compiler flags but it wasn't enough. I eventually gave up and installed Python via homebrew instead of asdf.

**Comment by danhper** [comment]
asdf-python is simply wrapping pyenv's python-build.
For build errors, please check pyenv issue tracker.
If it works with python-build but not with asdf-python please open another issue or comment here.

**Comment by mividtim** [comment]
@danhper The fix everyone is using for `python-build` is to export LDFLAGS and CPPFLAGS env vars to point to zlib installed with Homebrew, and re-run the Python install. However, running this plugin, it seems that these env vars are ignored - it always uses the zlib from xcode:
```
python-build: use zlib from xcode sdk
```
This seems like it's in your court to fix. `asdf-python` won't work on a brand-new Mac laptop. Will you help us out, or just point the finger elsewhere?

**Comment by Virviil** [comment]
Here is the solution that worked for me:

https://github.com/pyenv/pyenv/issues/1737#issuecomment-765724815

So it's possible to add the flag to asdf also:

```
CFLAGS=-Wno-implicit-function-declaration asdf install python 3.6.0
```
