### ISSUE TITLE
No such command in 2.7.15 of python

### ISSUE THREAD

**Issue by nesl247** [danhper/asdf-python#48]
This is using `2.7.15` installation. I'm using fish 3.0 if that matters at all.

**Comment by danhper** [comment]
Hi, sorry for the delay.
I did not manage to reproduce (I'm also using fish 3.0).
Could you try to uninstall and reinstall just to be sure, please?
Thanks.

**Comment by nesl247** [comment]
I've actually stopped using asdf as it wasn't working out for me. I'll close this then.

Thanks for trying to replicate it though!
