### ISSUE TITLE
Can't get running asdf-python with tkinter

### ISSUE THREAD

**Issue by AxelRHD** [danhper/asdf-python#50]
I am using asdf on an Ubuntu 18 desktop.
Python 3.7.2 is set up, and I am trying to get appJar running. It asks for tkinter-lib but I have no clue, how to put both ends together.

**Comment by oxitnik** [comment]
For tkinter to work, you need to have tkinter development files. Try installing package `tk-dev`:
`sudo apt-get install tk-dev` and reinstall python.

**Comment by danhper** [comment]
@oxitnik Thanks for the hint.
You will maybe also need to recompile python after installing these, I'm not sure.
Please comment here if it still does not work after installing development files.

**Comment by AxelRHD** [comment]
Thanks for the support. I will give it a try at the office after vacation.

**Comment by LRNZ09** [comment]
I'm having the same issue on macOS, latest version, did someone find a solution?

**Comment by jpinnix** [comment]
+1 for having this issue on macOS 10.15.5

**Comment by petern-sc** [comment]
https://stackoverflow.com/a/60469203/6847839

This solution worked for me on macOS

**Comment by skotchpine** [comment]
Building on @petern-sc's answer:
1. `brew install tcl-tk`
2. add env vars
3. `asdf uninstall` & `install` again

**Comment by kuzaxak** [comment]
Fresh guide:

* Uninstall python with asdf
* `brew install tcl-tk@8`
*
```
PATH="$(brew --prefix tcl-tk@8)/bin:$PATH" \
LDFLAGS="-L$(brew --prefix tcl-tk@8)/lib" \
CPPFLAGS="-I$(brew --prefix tcl-tk@8)/include" \
PKG_CONFIG_PATH="$(brew --prefix tcl-tk@8)/lib/pkgconfig" \
CFLAGS="-I$(brew --prefix tcl-tk@8)/include" \
PYTHON_CONFIGURE_OPTS="--with-tcltk-includes='-I$(brew --prefix tcl-tk@8)/include' --with-tcltk-libs='-L$(brew --prefix tcl-tk@8)/lib -ltcl8.6 -ltk8.6'" \
asdf install python 3.11.11
```
