### ISSUE TITLE
After installing Python with asdf I have a diferent version of cURL installed and running

### ISSUE THREAD

**Issue by rogeliozarate** [danhper/asdf-python#53]
I am not sure if this is Python, asdf or Emacs related but I have to start somewhere.
```bash
whereis curl
curl: /usr/bin/curl /home/cobi/.asdf/shims/curl /home/linuxbrew/.linuxbrew/bin/curl /usr/share/man/man1/curl.1.gz
```
Running Ubuntu 18.04.02 64 bits I had a version of cURL installed:
``` bash
/usr/bin/curl --version
curl 7.58.0 (x86_64-pc-linux-gnu) libcurl/7.58.0 OpenSSL/1.1.0g zlib/1.2.11 libidn2/2.0.4 libpsl/0.19.1 (+libidn2/2.0.4) nghttp2/1.30.0 librtmp/2.3
Release-Date: 2018-01-24
Protocols: dict file ftp ftps gopher http https imap imaps ldap ldaps pop3 pop3s rtmp rtsp smb smbs smtp smtps telnet tftp 
Features: AsynchDNS IDN IPv6 Largefile GSS-API Kerberos SPNEGO NTLM NTLM_WB SSL libz TLS-SRP HTTP2 UnixSockets HTTPS-proxy PSL
```
This particular version did not work well with Emacs and there was some issues about certificates, so I installed with HOMEBREW a different version:
```bash
/home/linuxbrew/.linuxbrew/bin/curl --version
curl 7.63.0 (x86_64-pc-linux-gnu) libcurl/7.63.0 OpenSSL/1.0.2q
Release-Date: 2018-12-12
Protocols: dict file ftp ftps gopher http https imap imaps pop3 pop3s rtsp smb smbs smtp smtps telnet tftp 
Features: AsynchDNS IPv6 Largefile NTLM NTLM_WB SSL TLS-SRP UnixSockets HTTPS-proxy 
```
After installing Python with asdf, I got this version working:
``` bash
asdf list
python
  3.7.0
  anaconda3-5.3.1
/home/cobi/.asdf/shims/curl --version
curl 7.61.0 (x86_64-conda_cos6-linux-gnu) libcurl/7.61.0 OpenSSL/1.0.2p zlib/1.2.11
Release-Date: 2018-07-11
Protocols: dict file ftp ftps gopher http https imap imaps pop3 pop3s rtsp smb smbs smtp smtps telnet tftp 
Features: AsynchDNS IPv6 Largefile NTLM NTLM_WB SSL libz TLS-SRP UnixSockets HTTPS-proxy 
```
Emacs uses cURL for several tasks inside some packages installed, like twittering-mode, to twit inside Emacs.
I do not know why Python 3.7.0 takes over the system installed cURL.
So far this particular version works ok in BASH CLI

**Comment by danhper** [comment]
What package is installing curl into shims?
Could you try `asdf which curl` please?
I would rather stick with the system curl unless you have a good reason not to.

**Comment by rogeliozarate** [comment]
Current global Python is 3.7.0, but the "conda" text in --version makes me think that the shim was installed by python-anaconda3-5.3.1.
```bash
$asdf which curl
No such plugin: curl
```
I agree with sticking to system cURL.

**Comment by danhper** [comment]
What version of asdf are you using?
This seems to be a fairly old error message.
Could you try with the latest version please?
Thanks!

**Comment by rogeliozarate** [comment]
Updated asdf to release v0.7.1
```bash
asdf which curl
/home/cobi/.asdf/installs/python/anaconda3-5.3.1/bin/curl
```

**Comment by danhper** [comment]
Ok, so the behavior seems perfectly normal but it is rather an incompatibility between the version of curl (or SSL certificates) provided by anaconda and emacs.
I am not sure if there is something I can do on my side to help for this. I would simply recommend to uninstall curl installed by anaconda and stick with the system version.

**Comment by rogeliozarate** [comment]
I agree with you.
It is surprising to me that a language version install his own cURL version.
Thanks for the help and the insights.

**Comment by danhper** [comment]
I think anaconda bundles up quite a few libraries which are usually provided by system packages to avoid version incompatibilities. I suppose it is possible to choose which libraries/executable anaconda should install but you should probably check anaconda documentation for that.

**Comment by rogeliozarate** [comment]
As a corollary, if someone gets here with a similar issue:
- Removed Python anaconda3-5.3.1 via asdf
- Upgraded cURL via brew
Emacs (Twittering mode) uses brew curl.
Working now.
Thanks a lot @danhper
