### ISSUE TITLE
How to use pyenv virtualenv?

### ISSUE THREAD

**Issue by viniciusban** [danhper/asdf-python#64]
Is there a way to use `pyenv virtualenv` with `asdf-python`?

I don't pollute the global Python environment with my packages. So, I create a virtualenv using `pyenv virtualenv`:

```
$ pyenv virtualenv 3.7.6 jupyter
$ pyenv activate jupyter
(jupyter) $ pip install jupyter matplotlib pandas scipy
(jupyter) $ pyenv deactivate
$ pyenv global 3.7.6 jupyter
```

Is there a way to achieve that with `asdf-python`?

Thanks in advance.

**Comment by alessod** [comment]
You can use the builtin [venv](https://docs.python.org/3.7/library/venv.html) command to create virutalenvs `python -m venv jupyter`. It will use the selected the python in your path, make sure to change python version `asdf shell python 3.7.6`.

**Comment by danhper** [comment]
I am not familiar with pyenv virtualenv but the builtin venv module should indeed work without any issue.
Please comment if you think this should be reopened.

**Comment by viniciusban** [comment]
Unfortunately, this suggestion does not work.

The caveat is having more than one python "version" active at the same time.

With the `pyenv-virtualenv` plugin, pyenv recognizes a virtualenv as if it was a python version, allowing me to do this:

```
$ pyenv global 3.7.6 jupyter_venv
```
Notice I am setting 3.7.6 and `jupyter_venv` at the same time as global python versions.

The command above sets the path in a way that if I issue the command `$ jupyter`, it will search it in the vanilla python 3.7.6 and, if not found, search for it inside the `jupyter_venv`.

I could not achieve it with asdf.

**Comment by gabrielmancini** [comment]
+1

**Comment by darkn3rd** [comment]
Is `.python-version` supported with support for virtualenv?
