### ISSUE TITLE
install python 3.8.3 failed

### ISSUE THREAD

**Issue by itaysk** [danhper/asdf-python#69]
Ubuntu 19.10
I've used asdf to install golang on this machine in the past. now trying to install python failed.
see the full log here: https://gist.githubusercontent.com/itaysk/deed1b3a34bbe6d02299b5ae44723f7d/raw/efc41af36826ad2b674b006138611d475d8221ad/python-build.20200602081612.15621.log

**Comment by jokrefta** [comment]
it looks like this is an issue with the [pyenv python-build plugin](https://github.com/pyenv/pyenv/tree/master/plugins/python-build), I get a similar error when I download python-build directly and try installing 3.8.3 with it

**Comment by itaysk** [comment]
fixed by 
```bash
sudo apt-get install libssl-dev libbz2-dev
```

**Comment by danhper** [comment]
Looks like it's working for you so I'll close. Please comment if there is still an issue on asdf-python's side.
