### ISSUE TITLE
pipenv and better Python dependency management

### ISSUE THREAD

**Issue by nomasprime** [danhper/asdf-python#71]
I'm new-ish to Python. I don't get why you'd use pipenv with asdf-python: isn't the latter, this repo, supposed to deal with managing separate environments?

If so, and pipenv is duplicating asdf-python functionality, is there a way to get Pipfile-like dependency management without pipenv?

As always, help much appreciated 🙏

**Comment by danhper** [comment]
Hi,
This repo is meant to manage multiple versions of Python, not multiple environments for Python.
I use asdf but typically create a new virtual environment for each project.
I hope this answers your question. Please comment if you have further questions.
