### ISSUE TITLE
Reshim doesn't seem to work

### ISSUE THREAD

**Issue by renatojf** [danhper/asdf-python#72]
```
$ pip3 list | grep gimme
gimme-aws-creds 2.3.4
```

```
$ gimme-aws-creds
zsh: command not found: gimme-aws-creds
```

```
$ asdf reshim python
$ gimme-aws-creds
zsh: command not found: gimme-aws-creds
```

Running this on `python -V => Python 3.8.3`
Can someone help me out?

**Comment by tz4678** [comment]
try `asdf global python system`

**Comment by danhper** [comment]
`asdf global python system` will use the Python system installation, which might not be desirable.
Reshim does not happen automatically so please run

```
asdf reshim python
```

after running pip install and it should work.
Please comment if this does not fix the issue.
