### ISSUE TITLE
Issues compiling the bz2 and sqlite3 extensions

### ISSUE THREAD

**Issue by SuperSonicHub1** [danhper/asdf-python#83]
When running `asdf install python latest`, I get:
```
python-build 3.9.1 /home/kyleanthonywilliams2/.asdf/installs/python/3.9.1
Downloading Python-3.9.1.tar.xz...
-> https://www.python.org/ftp/python/3.9.1/Python-3.9.1.tar.xz
Installing Python-3.9.1...
WARNING: The Python bz2 extension was not compiled. Missing the bzip2 lib?
WARNING: The Python sqlite3 extension was not compiled. Missing the SQLite3 lib?
Installed Python-3.9.1 to /home/kyleanthonywilliams2/.asdf/installs/python/3.9.1
```
I already have `libsqlite3-0` and `libbz2-1.0` installed from Debian's apt repository. Help?

**Comment by SuperSonicHub1** [comment]
I didn't. The repo manager simply took too long to reply so I closed the
issue.

**Comment by AntonOfTheWoods** [comment]
If anyone else gets this, you can follow the instructions (mentioned in the readme, it has to be admitted!) [here](https://github.com/pyenv/pyenv/wiki/Common-build-problems). Basically, you install all the devs python could possibly ever need to be compiled with, including for python2. Anyway, it works...

**Comment by SuperSonicHub1** [comment]
Thanks, must've been added after the two months I left the issue open.

**Comment by ksastan** [comment]
> If anyone else gets this, you can follow the instructions (mentioned in the readme, it has to be admitted!) [here](https://github.com/pyenv/pyenv/wiki/Common-build-problems). Basically, you install all the devs python could possibly ever need to be compiled with, including for python2. Anyway, it works...

Confirm the decision. Installing dev packages solve the problem. Ubuntu example:
```
apt install libsqlite3-dev
apt install libbz2-dev
```
then reinstall python
