### ISSUE TITLE
[Question] Local python installation disappeared.

### ISSUE THREAD

**Issue by INGCRENGIFO** [danhper/asdf-python#84]
Hi, I have manjaro with python 3.8, install asdf-python to use version 3.7 in a local project.

asdf local python 3.7

But now I see that python 3.7 remained global and the python that comes with my system (3.8) disappeared, is that normal?

if i run python 3.8 if it runs

**Comment by abrac** [comment]
I think you have to run the command `asdf global python system`, so that the system version of python is used.

**Comment by INGCRENGIFO** [comment]
Thank you @abrac
